import type { Skill, SkillCategoryMeta } from '@/types';

export const skillCategories: SkillCategoryMeta[] = [
  { id: 'languages', label: 'Languages', command: 'skills --category=languages' },
  { id: 'web', label: 'Web', command: 'skills --category=web' },
  { id: 'ai-ml', label: 'AI / ML', command: 'skills --category=ai-ml' },
  { id: 'tools', label: 'Tools', command: 'skills --category=tools' },
];

export const skills: Skill[] = [
  // Languages
  {
    name: 'Python',
    category: 'languages',
    icon: 'Python',
    proficiency: 5,
    note: 'Primary language for ML pipelines, FastAPI services, and research tooling.',
    relatedProjectSlug: 'deep-researcher-rag-system',
  },
  {
    name: 'TypeScript',
    category: 'languages',
    icon: 'TypeScript',
    proficiency: 5,
    note: 'Used across full-stack apps with strict typing and API contracts.',
    relatedProjectSlug: 'ideaclinic-forum',
  },
  {
    name: 'JavaScript',
    category: 'languages',
    icon: 'JavaScript',
    proficiency: 4,
    note: 'Real-time chat clients and Node.js backends.',
    relatedProjectSlug: 'minglemate',
  },
  {
    name: 'Java',
    category: 'languages',
    icon: 'Java',
    proficiency: 4,
    note: 'Spring Boot services for enterprise web portals.',
    relatedProjectSlug: 'food-ordering-system',
  },
  {
    name: 'C++',
    category: 'languages',
    icon: 'C++',
    proficiency: 4,
    note: 'Competitive programming and systems-oriented coursework.',
  },
  {
    name: 'SQL',
    category: 'languages',
    icon: 'SQL',
    proficiency: 4,
    note: 'Schema design and query optimization for production APIs.',
    relatedProjectSlug: 'ideaclinic-forum',
  },
  {
    name: 'Go',
    category: 'languages',
    icon: 'Go',
    proficiency: 3,
    note: 'Building concurrent backend services and scalable APIs.',
  },
  {
    name: 'Rust',
    category: 'languages',
    icon: 'Rust',
    proficiency: 3,
    note: 'Exploring systems programming with memory safety guarantees and high performance.',
  },
  // Web
  {
    name: 'React',
    category: 'web',
    icon: 'React',
    proficiency: 5,
    note: 'Component-driven UIs with hooks, context, and real-time updates.',
    relatedProjectSlug: 'minglemate',
  },
  {
    name: 'React Native',
    category: 'web',
    icon: 'React', // Using React icon as a fallback if React Native icon isn't explicitly defined
    proficiency: 4,
    note: 'Building cross-platform mobile applications.',
  },
  {
    name: 'Next.js',
    category: 'web',
    icon: 'Next.js',
    proficiency: 5,
    note: 'App Router, SSR, and MDX-powered portfolio and product sites.',
    relatedProjectSlug: 'ideaclinic-forum',
  },
  {
    name: 'Node.js',
    category: 'web',
    icon: 'Node.js',
    proficiency: 4,
    note: 'REST APIs and WebSocket servers for concurrent chat workloads.',
    relatedProjectSlug: 'minglemate',
  },
  {
    name: 'Express',
    category: 'web',
    icon: 'Express',
    proficiency: 4,
    note: 'Middleware-heavy REST APIs with JWT auth and rate limiting.',
    relatedProjectSlug: 'minglemate',
  },
  {
    name: 'Tailwind CSS',
    category: 'web',
    icon: 'Tailwind CSS',
    proficiency: 5,
    note: 'Utility-first styling with theme tokens and responsive layouts.',
    relatedProjectSlug: 'ideaclinic-forum',
  },
  {
    name: 'MongoDB',
    category: 'web',
    icon: 'MongoDB',
    proficiency: 4,
    note: 'Indexed collections for chat history and user sessions.',
    relatedProjectSlug: 'minglemate',
  },
  {
    name: 'PostgreSQL',
    category: 'web',
    icon: 'PostgreSQL',
    proficiency: 4,
    note: 'Relational schemas with Drizzle ORM and Supabase backends.',
    relatedProjectSlug: 'ideaclinic-forum',
  },
  // AI / ML
  {
    name: 'TensorFlow',
    category: 'ai-ml',
    icon: 'TensorFlow',
    proficiency: 4,
    note: 'CNN training pipelines for image classification tasks.',
    relatedProjectSlug: 'human-emotion-classifier',
  },
  {
    name: 'PyTorch',
    category: 'ai-ml',
    icon: 'PyTorch',
    proficiency: 4,
    note: 'MovieNet-style action recognition with 97% training accuracy.',
    relatedProjectSlug: 'video-action-recognition',
  },
  {
    name: 'LangChain',
    category: 'ai-ml',
    icon: 'LangChain',
    proficiency: 4,
    note: 'Multi-agent orchestration for retrieval-augmented research.',
    relatedProjectSlug: 'deep-researcher-rag-system',
  },
  {
    name: 'FastAPI',
    category: 'ai-ml',
    icon: 'FastAPI',
    proficiency: 4,
    note: 'Async Python APIs serving ML inference endpoints.',
    relatedProjectSlug: 'ai-text-summarization',
  },
  {
    name: 'OpenCV',
    category: 'ai-ml',
    icon: 'OpenCV',
    proficiency: 3,
    note: 'Preprocessing pipelines for computer vision experiments.',
    relatedProjectSlug: 'human-emotion-classifier',
  },
  {
    name: 'HuggingFace',
    category: 'ai-ml',
    icon: 'HuggingFace',
    proficiency: 3,
    note: 'Transformer models for NLP summarization workflows.',
    relatedProjectSlug: 'ai-text-summarization',
  },
  {
    name: 'Scikit-learn',
    category: 'ai-ml',
    icon: 'Python', // Fallback icon
    proficiency: 4,
    note: 'Building predictive models for regression and classification tasks.',
  },
  {
    name: 'Pandas',
    category: 'ai-ml',
    icon: 'Python', // Fallback icon
    proficiency: 4,
    note: 'Data manipulation and analysis for ML pipelines.',
  },
  // Tools
  {
    name: 'Docker',
    category: 'tools',
    icon: 'Docker',
    proficiency: 4,
    note: 'Containerized deployments with 99.5% uptime in production.',
    relatedProjectSlug: 'deep-researcher-rag-system',
  },
  {
    name: 'GitHub',
    category: 'tools',
    icon: 'GitHub',
    proficiency: 5,
    note: 'Version control, CI workflows, and open-source project hosting.',
    relatedProjectSlug: 'deep-researcher-rag-system',
  },
  {
    name: 'AWS',
    category: 'tools',
    icon: 'AWS',
    proficiency: 3,
    note: 'Cloud foundations and ML deployment basics.',
  },
  {
    name: 'Supabase',
    category: 'tools',
    icon: 'Supabase',
    proficiency: 4,
    note: 'Real-time Postgres with row-level security for forum apps.',
    relatedProjectSlug: 'ideaclinic-forum',
  },
  {
    name: 'Socket.io',
    category: 'tools',
    icon: 'Socket.io',
    proficiency: 4,
    note: 'Bidirectional WebSockets for 100+ concurrent chat users.',
    relatedProjectSlug: 'minglemate',
  },
  {
    name: 'Vite',
    category: 'tools',
    icon: 'Vite', // Assuming Vite icon exists or string matching handles it
    proficiency: 4,
    note: 'Next-generation frontend tooling for fast React builds.',
  },
];
